### ISSUE TITLE
It seems that OpenZepplin has changed its directory structure.

### ISSUE THREAD

**Issue by lmatz** [aave/flashloan-box#21]
``https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/math/SafeMath.sol``

has changed to 

``https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/math/SafeMath.sol``

The `import` statement may need to be changed accordingly.

**Comment by ubuntunewdev100** [comment]
ikr, what a mess, i cant get it to work, i changed manually alot of the paths, now it tells me the compilation version is not correct?

**Comment by lmatz** [comment]
> ikr, what a mess, i cant get it to work, i changed manually alot of the paths, now it tells me the compilation version is not correct?

I gave it up :pensive:, trying to create a new one with key functionalities from scratch
