### ISSUE TITLE
Provider Value needs to be wrapped in function

### ISSUE THREAD

**Issue by JChiaramonte7** [aave/flashloan-box#5]
As per: https://www.trufflesuite.com/tutorials/using-infura-custom-provider
> The provider value is wrapped in a function, which ensures that it won't get initialized until it's needed. This is especially important if connecting to multiple networks. (See the Networks configuration section of the documentation for more on this topic.)

example: 
```
provider: () => new HDWalletProvider(process.env.DEPLOYMENT_ACCOUNT_KEY, "https://mainnet.infura.io/" + process.env.INFURA_API_KEY),
```
for all networks

**Comment by mrdavey** [comment]
Hey @JChiaramonte7, thanks for pointing that out. The linked article is from 2016 and outdated. It should work the way it currently is set up in this box.
